"""seed expanded global Buddhist digital resource sources

Revision ID: 0021
Revises: 0020
Create Date: 2026-03-02
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0021"
down_revision: Union[str, None] = "0020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ── New data sources to add (deduped against existing 175) ──
SOURCES = [
    # ===== 巴利/上座部 =====
    {
        "code": "digital-pali-reader",
        "name_zh": "数字巴利读本",
        "name_en": "Digital Pali Reader",
        "base_url": "https://www.digitalpalireader.online/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "巴利三藏在线阅读工具，含语法分析与字典查询",
    },
    {
        "code": "tipitaka-org",
        "name_zh": "Tipitaka.org 世界巴利三藏",
        "name_en": "Tipitaka.org World Tipitaka Edition",
        "base_url": "https://tipitaka.org/",
        "access_type": "external",
        "region": "泰国",
        "languages": "pi,en,th",
        "description": "朱拉隆功大学主持的多脚本巴利三藏（罗马、泰文、缅文、僧伽罗等多种字体）",
    },
    {
        "code": "ancient-buddhist-texts",
        "name_zh": "古代佛教经典网",
        "name_en": "Ancient Buddhist Texts",
        "base_url": "https://www.ancient-buddhist-texts.net/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "Ānandajoti Bhikkhu 的巴利文本、翻译与语法分析",
    },
    {
        "code": "dhammatalks",
        "name_zh": "法谈网",
        "name_en": "Dhammatalks.org",
        "base_url": "https://www.dhammatalks.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "pi,en",
        "description": "坦尼沙罗比丘(Thanissaro Bhikkhu)巴利经藏英译全集",
    },
    {
        "code": "palikanon",
        "name_zh": "巴利正典德语网",
        "name_en": "Palikanon.com",
        "base_url": "https://www.palikanon.com/",
        "access_type": "external",
        "region": "德国",
        "languages": "pi,de,en",
        "description": "巴利三藏德语翻译与巴利原文对照",
    },
    {
        "code": "suttafriends",
        "name_zh": "庄春江巴利经藏",
        "name_en": "Sutta Friends (Zhuang Chunjiang)",
        "base_url": "https://agama.buddhason.org/",
        "access_type": "external",
        "region": "台湾",
        "languages": "pi,lzh",
        "description": "庄春江工作站：巴利经藏中译与阿含经对读",
    },
    {
        "code": "readingfaithfully",
        "name_zh": "忠实阅读巴利文",
        "name_en": "ReadingFaithfully.org",
        "base_url": "https://readingfaithfully.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "巴利三藏阅读指南与工具集合",
    },
    # ===== 藏文/藏传 =====
    {
        "code": "lotsawa-house",
        "name_zh": "译师之家",
        "name_en": "Lotsawa House",
        "base_url": "https://www.lotsawahouse.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,en,fr,de,ja,ko,lzh",
        "description": "藏传佛教经典翻译项目，含大量仁波切教言与经论翻译",
    },
    {
        "code": "rkts",
        "name_zh": "甘珠尔丹珠尔研究资源",
        "name_en": "Resources for Kanjur & Tanjur Studies",
        "base_url": "https://www.istb.univie.ac.at/kanjur/rktsneu/sub/index.php",
        "access_type": "external",
        "region": "奥地利",
        "languages": "bo,sa,en",
        "description": "维也纳大学主持的甘珠尔与丹珠尔研究数据库，含版本比对",
    },
    {
        "code": "treasury-of-lives",
        "name_zh": "生命宝库藏传传记",
        "name_en": "Treasury of Lives",
        "base_url": "https://treasuryoflives.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "bo,en",
        "description": "藏传佛教人物传记百科全书，含超5000位高僧大德传记",
    },
    {
        "code": "buddhanexus",
        "name_zh": "佛典对比平台 BuddhaNexus",
        "name_en": "BuddhaNexus",
        "base_url": "https://buddhanexus.net/",
        "access_type": "external",
        "region": "德国",
        "languages": "bo,sa,pi,lzh",
        "description": "汉堡大学多语种佛典平行文本智能匹配与对比平台",
    },
    {
        "code": "acip",
        "name_zh": "亚洲经典输入项目",
        "name_en": "Asian Classics Input Project",
        "base_url": "https://www.asianclassics.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "bo,sa",
        "description": "数字化藏传佛教经典文本，含甘丹寺等寺院馆藏",
    },
    {
        "code": "tsadra",
        "name_zh": "擦札基金会数字图书馆",
        "name_en": "Tsadra Foundation",
        "base_url": "https://www.tsadra.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "bo,en",
        "description": "藏传佛教经典翻译与学术出版，含多部重要论典英译",
    },
    {
        "code": "adarsha",
        "name_zh": "明镜藏文大藏经",
        "name_en": "Adarsha",
        "base_url": "https://adarsha.dharma-treasure.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "bo",
        "description": "法宝基金会(Dharma Treasure)藏文大藏经OCR校对全文检索",
    },
    {
        "code": "thl",
        "name_zh": "藏喜马拉雅图书馆",
        "name_en": "Tibetan & Himalayan Library",
        "base_url": "https://www.thlib.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "bo,en",
        "description": "弗吉尼亚大学藏学综合资源平台，含藏语词典、地名数据库",
    },
    {
        "code": "rigpa-wiki",
        "name_zh": "日巴百科",
        "name_en": "Rigpa Wiki",
        "base_url": "https://www.rigpawiki.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,en",
        "description": "藏传佛教百科全书式Wiki，索甲仁波切传承",
    },
    # ===== 梵文/印度学 =====
    {
        "code": "sarit",
        "name_zh": "印度文本检索平台 SARIT",
        "name_en": "Search and Retrieval of Indic Texts",
        "base_url": "https://sarit.indology.info/",
        "access_type": "external",
        "region": "德国",
        "languages": "sa,pi,en",
        "description": "哥廷根大学梵文/巴利文/普拉克里特文电子文本检索与校勘平台",
    },
    {
        "code": "titus",
        "name_zh": "TITUS 印欧语文本库",
        "name_en": "Thesaurus Indogermanischer Text- und Sprachmaterialien",
        "base_url": "https://titus.uni-frankfurt.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "sa,pi,xto,txb,sog,kho",
        "description": "法兰克福大学印欧语系文本数据库，含梵/巴利/吐火罗佛教文本",
    },
    {
        "code": "muktabodha",
        "name_zh": "解脱觉图书馆",
        "name_en": "Muktabodha Digital Library",
        "base_url": "https://www.muktabodha.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "sa",
        "description": "梵文手稿数字化项目（含密教文献），印度各地收集",
    },
    {
        "code": "sanskritdocuments",
        "name_zh": "梵文文献网",
        "name_en": "Sanskrit Documents",
        "base_url": "https://sanskritdocuments.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "sa",
        "description": "开源梵文电子文本（含佛教、印度教、耆那教文献），Unicode天城体",
    },
    # ===== 写本/手稿项目 =====
    {
        "code": "schoyen-collection",
        "name_zh": "斯科延收藏佛教写本",
        "name_en": "Schøyen Collection",
        "base_url": "https://www.schoyencollection.com/",
        "access_type": "external",
        "region": "挪威",
        "languages": "sa,pgd,kho,bo",
        "description": "全球最大私人写本收藏之一，含犍陀罗语佛经残片与梵文贝叶经",
    },
    {
        "code": "ngmcp",
        "name_zh": "尼泊尔-德国写本编目项目",
        "name_en": "Nepal-German Manuscript Cataloguing Project",
        "base_url": "https://catalogue.ngmcp.uni-hamburg.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "sa,bo",
        "description": "汉堡大学与尼泊尔国家档案馆合作的梵文写本编目与数字化",
    },
    {
        "code": "fpl",
        "name_zh": "脆弱贝叶写本项目",
        "name_en": "Fragile Palm Leaves Foundation",
        "base_url": "https://fragile-palm-leaves.org/",
        "access_type": "external",
        "region": "泰国",
        "languages": "pi,my,th,km",
        "description": "东南亚贝叶经手稿保存与数字化基金会",
    },
    {
        "code": "dreamsea",
        "name_zh": "东南亚濒危写本数字库",
        "name_en": "DREAMSEA",
        "base_url": "https://dreamsea.co/",
        "access_type": "external",
        "region": "德国",
        "languages": "pi,my,th,km",
        "description": "汉堡大学东南亚濒危写本数字化保存项目",
    },
    {
        "code": "cetom",
        "name_zh": "吐火罗语写本全集",
        "name_en": "A Comprehensive Edition of Tocharian Manuscripts",
        "base_url": "https://www.univie.ac.at/tocharian/",
        "access_type": "external",
        "region": "奥地利",
        "languages": "xto,txb",
        "description": "维也纳大学吐火罗语佛教写本数字化全集，含A/B两种方言",
    },
    # ===== 中文/东亚 =====
    {
        "code": "ctext",
        "name_zh": "中国哲学书电子化计划",
        "name_en": "Chinese Text Project",
        "base_url": "https://ctext.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,en",
        "description": "大型先秦两汉文献数据库，含佛教典籍分类，提供全文检索",
    },
    {
        "code": "agama",
        "name_zh": "阿含经数字典藏",
        "name_en": "Agama Digital Archive",
        "base_url": "https://agamaresearch.dila.edu.tw/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,pi,sa",
        "description": "DILA 阿含经研究资源，含四阿含与巴利尼柯耶对照",
    },
    {
        "code": "xuanzang-project",
        "name_zh": "玄奘译经数字工程",
        "name_en": "Xuanzang Translation Project",
        "base_url": "https://www.xuanzang.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,sa,en",
        "description": "玄奘三藏翻译佛典的数字化研究与梵汉对照",
    },
    # ===== 日文/日本学 =====
    {
        "code": "inbuds",
        "name_zh": "印度学佛教学论文数据库",
        "name_en": "INBUDS Indian and Buddhist Studies Database",
        "base_url": "https://www.inbuds.net/",
        "access_type": "external",
        "region": "日本",
        "languages": "ja,en,lzh",
        "description": "日本印度学佛教学会论文数据库，含10万篇以上学术论文目录",
    },
    {
        "code": "sat-iiif",
        "name_zh": "SAT 大正藏影像数据库",
        "name_en": "SAT Image Database",
        "base_url": "https://dzkimgs.l.u-tokyo.ac.jp/SATi/images.php",
        "access_type": "external",
        "region": "日本",
        "languages": "lzh,ja",
        "description": "东京大学 SAT 大正新修大藏经页面影像 IIIF 数据库",
    },
    {
        "code": "jairo",
        "name_zh": "日本学术机构知识库",
        "name_en": "JAIRO Japan Institutional Repositories",
        "base_url": "https://irdb.nii.ac.jp/",
        "access_type": "external",
        "region": "日本",
        "languages": "ja,en",
        "description": "日本机构知识库门户，可检索佛学学位论文与研究报告",
    },
    {
        "code": "zenbunka",
        "name_zh": "禅文化研究所数字档案",
        "name_en": "Institute for Zen Studies Digital Archive",
        "base_url": "https://www.zenbunka.or.jp/",
        "access_type": "external",
        "region": "日本",
        "languages": "lzh,ja",
        "description": "花园大学禅文化研究所电子禅籍与禅宗人名辞典",
    },
    # ===== 韩文/韩国学 =====
    {
        "code": "kabc",
        "name_zh": "韩国佛教文化事业团",
        "name_en": "Korean Association for Buddhist Culture",
        "base_url": "https://www.buddhism.or.kr/",
        "access_type": "external",
        "region": "韩国",
        "languages": "ko,lzh",
        "description": "韩国佛教文化事业团电子佛典与佛教文化资源",
    },
    {
        "code": "abc-tripitaka",
        "name_zh": "韩国佛教典籍丛书",
        "name_en": "ABC - Anthology of Buddhist Canonical Texts",
        "base_url": "https://kabc.dongguk.edu/",
        "access_type": "external",
        "region": "韩国",
        "languages": "ko,lzh",
        "description": "东国大学韩国佛教全书电子化，含韩国撰述佛典",
    },
    # ===== 百科/辞典/参考 =====
    {
        "code": "buddhanet",
        "name_zh": "佛网 BuddhaNet",
        "name_en": "BuddhaNet",
        "base_url": "https://www.buddhanet.net/",
        "access_type": "external",
        "region": "澳大利亚",
        "languages": "en,pi",
        "description": "佛教信息与教育网络，含电子书库、冥想指南与全球寺院目录",
    },
    {
        "code": "buddhistdoor",
        "name_zh": "佛门网",
        "name_en": "Buddhistdoor Global",
        "base_url": "https://www.buddhistdoor.net/",
        "access_type": "external",
        "region": "中国香港",
        "languages": "en,lzh",
        "description": "全球佛教新闻与文化平台，含佛学辞典与学术文章",
    },
    {
        "code": "dhammawiki",
        "name_zh": "法义百科",
        "name_en": "Dhamma Wiki",
        "base_url": "https://dhammawiki.com/",
        "access_type": "external",
        "region": "国际",
        "languages": "en,pi",
        "description": "开放编辑的上座部佛教百科全书",
    },
    {
        "code": "suttacentral-voice",
        "name_zh": "SuttaCentral 语音",
        "name_en": "SuttaCentral Voice",
        "base_url": "https://voice.suttacentral.net/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en,de",
        "description": "SuttaCentral 经文语音朗读项目，辅助视障用户阅读",
    },
    {
        "code": "gandhari-dict",
        "name_zh": "犍陀罗语辞典",
        "name_en": "A Dictionary of Gāndhārī",
        "base_url": "https://gandhari.org/dictionary",
        "access_type": "external",
        "region": "美国",
        "languages": "pgd,sa,en",
        "description": "华盛顿大学犍陀罗语专业辞典，含词源与用例",
    },
    # ===== 东南亚 =====
    {
        "code": "thai-digitalcollections",
        "name_zh": "泰国数字馆藏",
        "name_en": "Thai Digital Collections",
        "base_url": "https://tdc.thailis.or.th/",
        "access_type": "external",
        "region": "泰国",
        "languages": "th,pi",
        "description": "泰国高校联合数字馆藏，含佛教写本与学位论文",
    },
    {
        "code": "myanmar-digital-lib",
        "name_zh": "缅甸数字图书馆",
        "name_en": "Myanmar Digital Library",
        "base_url": "https://www.myanmardigitallibrary.com/",
        "access_type": "external",
        "region": "缅甸",
        "languages": "my,pi",
        "description": "缅甸贝叶经与佛教文献数字化，含上座部注疏",
    },
    {
        "code": "sinhala-tripitaka",
        "name_zh": "僧伽罗语三藏电子版",
        "name_en": "Sinhala Tipitaka Online",
        "base_url": "https://tipitaka.lk/",
        "access_type": "external",
        "region": "斯里兰卡",
        "languages": "si,pi",
        "description": "斯里兰卡巴利三藏僧伽罗语翻译全文在线版",
    },
    # ===== 跨传统/比较研究 =====
    {
        "code": "early-buddhist-texts",
        "name_zh": "早期佛教文本项目",
        "name_en": "Early Buddhist Texts Project",
        "base_url": "https://suttacentral.net/editions",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,lzh,sa,en",
        "description": "菩提比丘(Bhikkhu Bodhi)与比丘沙马(Bhikkhu Sujato)早期佛典翻译",
    },
    {
        "code": "buddhiststudies-info",
        "name_zh": "佛学研究信息门户",
        "name_en": "Buddhist Studies WWW Virtual Library",
        "base_url": "https://www.buddhismuskunde.uni-hamburg.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "en,de",
        "description": "汉堡大学维护的佛学研究虚拟图书馆，学术资源导航",
    },
    {
        "code": "numata-center",
        "name_zh": "沼田佛教翻译研究中心",
        "name_en": "Numata Center for Buddhist Translation",
        "base_url": "https://www.numatacenter.com/",
        "access_type": "external",
        "region": "美国",
        "languages": "en,lzh,ja",
        "description": "BDK 英译大藏经出版方，致力于汉文佛典英译",
    },
    {
        "code": "gandhari-scrolls",
        "name_zh": "犍陀罗语卷轴早期佛典",
        "name_en": "Early Buddhist Manuscripts Project",
        "base_url": "https://ebmp.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "pgd,sa",
        "description": "华盛顿大学早期佛教写本项目，研究犍陀罗语桦皮卷轴",
    },
    # ===== 蒙古/中亚补充 =====
    {
        "code": "buryat-buddhism",
        "name_zh": "布里亚特佛教文献",
        "name_en": "Buryat Buddhist Archives",
        "base_url": "https://www.imbtit.ru/",
        "access_type": "external",
        "region": "俄罗斯",
        "languages": "cmg,bo",
        "description": "俄罗斯布里亚特共和国蒙古语佛教文献与藏文写本",
    },
    {
        "code": "kalmyk-buddhism",
        "name_zh": "卡尔梅克佛教文献",
        "name_en": "Kalmyk Buddhist Heritage",
        "base_url": "https://www.kigiran.com/",
        "access_type": "external",
        "region": "俄罗斯",
        "languages": "cmg,bo",
        "description": "卡尔梅克共和国蒙古语佛教写本与学术研究",
    },
    {
        "code": "tuva-buddhism",
        "name_zh": "图瓦佛教文献中心",
        "name_en": "Tuvan Buddhist Heritage Center",
        "base_url": "https://www.tuvaonline.ru/",
        "access_type": "external",
        "region": "俄罗斯",
        "languages": "bo,cmg",
        "description": "图瓦共和国佛教写本与藏传佛教文化遗产数字化",
    },
    # ===== 欧洲学术补充 =====
    {
        "code": "bristol-pali",
        "name_zh": "布里斯托大学巴利文本项目",
        "name_en": "University of Bristol Pali Text Project",
        "base_url": "https://www.bristol.ac.uk/",
        "access_type": "external",
        "region": "英国",
        "languages": "pi,en",
        "description": "布里斯托大学巴利文献校勘与注疏研究项目",
    },
    {
        "code": "munich-indology",
        "name_zh": "慕尼黑大学印度学佛教数字化",
        "name_en": "LMU Munich Indology Digital",
        "base_url": "https://www.indologie.uni-muenchen.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "sa,pi,de",
        "description": "慕尼黑大学印度学系梵文佛教文本数字化项目",
    },
    {
        "code": "paris-buddhism",
        "name_zh": "巴黎大学佛学研究中心",
        "name_en": "Université de Paris Buddhist Studies",
        "base_url": "https://www.ephe.psl.eu/",
        "access_type": "external",
        "region": "法国",
        "languages": "fr,sa,bo,lzh",
        "description": "巴黎高等研究实践学院佛教学科研究与写本数字化",
    },
    # ===== 现代翻译项目 =====
    {
        "code": "khyentse-translation",
        "name_zh": "钦哲翻译项目",
        "name_en": "Khyentse Foundation Translations",
        "base_url": "https://khyentsefoundation.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,en",
        "description": "宗萨钦哲仁波切基金会资助的藏传经典翻译项目",
    },
    {
        "code": "shambhala-translations",
        "name_zh": "香巴拉翻译委员会",
        "name_en": "Nalanda Translation Committee",
        "base_url": "https://nalandatranslation.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "bo,en",
        "description": "创巴仁波切传承的藏传佛教经典翻译项目",
    },
    {
        "code": "padmakara",
        "name_zh": "莲花翻译小组",
        "name_en": "Padmakara Translation Group",
        "base_url": "https://www.padmakara.org/",
        "access_type": "external",
        "region": "法国",
        "languages": "bo,en,fr",
        "description": "藏传佛教经典的英法语翻译出版项目",
    },
    # ===== 印度/南亚补充 =====
    {
        "code": "ignca",
        "name_zh": "印度甘地国家艺术中心",
        "name_en": "Indira Gandhi National Centre for the Arts",
        "base_url": "https://www.ignca.gov.in/",
        "access_type": "external",
        "region": "印度",
        "languages": "sa,pi,en",
        "description": "含数字化梵文佛教写本与印度佛教遗址数据库",
    },
    {
        "code": "nmc-india",
        "name_zh": "印度国家写本使命",
        "name_en": "National Mission for Manuscripts, India",
        "base_url": "https://www.namami.gov.in/",
        "access_type": "external",
        "region": "印度",
        "languages": "sa,pi,en",
        "description": "印度政府写本保护与数字化国家计划，含佛教贝叶经",
    },
    # ===== 数字人文/技术工具 =====
    {
        "code": "cbeta-api",
        "name_zh": "CBETA API 开放接口",
        "name_en": "CBETA Online API",
        "base_url": "https://cbdata.dila.edu.tw/",
        "access_type": "api",
        "region": "台湾",
        "languages": "lzh",
        "description": "CBETA 中华电子佛典 RESTful API，提供结构化经典数据",
    },
    {
        "code": "dharmanexus",
        "name_zh": "法典知识图谱",
        "name_en": "DharmaNexus Knowledge Graph",
        "base_url": "https://dharmanexus.net/",
        "access_type": "external",
        "region": "国际",
        "languages": "sa,pi,bo,lzh,en",
        "description": "基于AI的佛教概念知识图谱与经典交叉引用平台",
    },
    # ===== 汉传佛教补充 =====
    {
        "code": "mahayana-texts",
        "name_zh": "大乘经典数字项目",
        "name_en": "Mahayana Texts Digital Project",
        "base_url": "https://www.mahayanatext.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,sa,en",
        "description": "大乘佛教重要经典的多语种对照与学术研究",
    },
    {
        "code": "hua-yan",
        "name_zh": "华严学数字资源",
        "name_en": "Huayan Studies Digital Resources",
        "base_url": "https://www.huayanzang.com/",
        "access_type": "external",
        "region": "中国",
        "languages": "lzh",
        "description": "华严经及华严宗典籍的数字化与学术研究资源",
    },
    {
        "code": "chan-buddhism",
        "name_zh": "禅宗典籍数据库",
        "name_en": "Chan/Zen Buddhist Texts Database",
        "base_url": "https://www.thezensite.com/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,ja,en",
        "description": "禅宗/曹洞宗/临济宗公案、语录与论著的多语种数字化",
    },
    {
        "code": "pure-land-texts",
        "name_zh": "净土宗典籍数字化",
        "name_en": "Pure Land Buddhist Texts Online",
        "base_url": "https://www.purelandbuddhism.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,ja,en",
        "description": "净土三经及净土宗祖师著作的多语种数字化",
    },
]


def upgrade() -> None:
    from sqlalchemy.sql import text as sa_text

    conn = op.get_bind()

    inserted = 0
    updated = 0
    for s in SOURCES:
        result = conn.execute(
            sa_text("SELECT id FROM data_sources WHERE code = :code"),
            {"code": s["code"]},
        )
        row = result.fetchone()
        if row:
            # Update existing record with new fields
            conn.execute(
                sa_text("""
                    UPDATE data_sources
                    SET name_zh = :name_zh,
                        name_en = :name_en,
                        base_url = :base_url,
                        access_type = :access_type,
                        region = :region,
                        languages = :languages,
                        description = :description
                    WHERE code = :code
                """),
                s,
            )
            updated += 1
        else:
            conn.execute(
                sa_text("""
                    INSERT INTO data_sources (code, name_zh, name_en, base_url, access_type, region, languages, description, is_active)
                    VALUES (:code, :name_zh, :name_en, :base_url, :access_type, :region, :languages, :description, true)
                """),
                s,
            )
            inserted += 1

    print(f"  → Inserted {inserted} new sources, updated {updated} existing")


def downgrade() -> None:
    from sqlalchemy.sql import text as sa_text

    conn = op.get_bind()
    codes = [s["code"] for s in SOURCES]
    for code in codes:
        conn.execute(
            sa_text("DELETE FROM data_sources WHERE code = :code"),
            {"code": code},
        )
