"""seed additional Buddhist digital resources from comprehensive research

Revision ID: 0022
Revises: 0021
Create Date: 2026-03-02
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0022"
down_revision: Union[str, None] = "0021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ── New data sources identified via comprehensive web research ──
SOURCES = [
    # ===== 巴利/上座部工具 =====
    {
        "code": "tipitakapali-org",
        "name_zh": "Tipitakapali.org 巴利三藏",
        "name_en": "Tipitakapali.org",
        "base_url": "https://tipitakapali.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi",
        "description": "巴利三藏在线阅读，含多种文字编码（天城文、僧伽罗等）",
    },
    {
        "code": "tipitaka-app",
        "name_zh": "Tipitaka App 巴利三藏应用",
        "name_en": "Tipitaka Pali Projector",
        "base_url": "https://tipitaka.app/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "现代化巴利三藏 Web 应用，含多语翻译和跨引用",
    },
    {
        "code": "tipitaka-lk",
        "name_zh": "斯里兰卡巴利三藏",
        "name_en": "Tipitaka.lk",
        "base_url": "https://tipitaka.lk/",
        "access_type": "external",
        "region": "斯里兰卡",
        "languages": "pi,si,en",
        "description": "斯里兰卡 Buddha Jayanti Tripitaka 在线版",
    },
    {
        "code": "dpd-dict",
        "name_zh": "数字巴利辞典 DPD",
        "name_en": "Digital Pali Dictionary",
        "base_url": "https://dpdict.net/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "最全面的开源巴利-英语辞典，含词根分析与语法标注",
    },
    {
        "code": "cpd-cologne",
        "name_zh": "科隆巴利批判辞典",
        "name_en": "Critical Pali Dictionary (CPD)",
        "base_url": "https://cpd.uni-koeln.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "pi,en,de",
        "description": "丹麦皇家学院巴利批判辞典，现由科隆大学数字化",
    },
    {
        "code": "pali-dict-sutta",
        "name_zh": "巴利辞典工具集",
        "name_en": "Pali Dictionary & Sutta Tools",
        "base_url": "https://dictionary.sutta.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "集成多部巴利辞典（PED、CPD、DPD）的统一查询界面",
    },
    {
        "code": "simsapa-dhamma",
        "name_zh": "Simsapa 巴利法宝",
        "name_en": "Simsapa Dhamma Reader",
        "base_url": "https://simsapa.github.io/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "开源桌面巴利三藏阅读器，含辞典与搜索功能",
    },
    {
        "code": "tipitaka-net",
        "name_zh": "巴利三藏在线 Tipitaka.net",
        "name_en": "Tipitaka Network",
        "base_url": "https://www.tipitaka.net/",
        "access_type": "external",
        "region": "泰国",
        "languages": "pi,th,en",
        "description": "泰国巴利三藏在线查阅与比较",
    },
    {
        "code": "ped-dsal",
        "name_zh": "PED 巴利-英语辞典",
        "name_en": "Pali-English Dictionary (PED/DSAL)",
        "base_url": "https://dsal.uchicago.edu/dictionaries/pali/",
        "access_type": "external",
        "region": "美国",
        "languages": "pi,en",
        "description": "T.W. Rhys Davids / William Stede 巴利-英语辞典在线版 (Chicago DSAL)",
    },
    {
        "code": "dllm-laos",
        "name_zh": "老挝数字手稿图书馆",
        "name_en": "Digital Library of Lao Manuscripts (DLLM)",
        "base_url": "https://www.laomanuscripts.net/",
        "access_type": "external",
        "region": "老挝",
        "languages": "lo,pi",
        "description": "老挝贝叶经与佛教手稿数字化馆藏",
    },
    {
        "code": "seadl-niu",
        "name_zh": "东南亚数字图书馆",
        "name_en": "Southeast Asian Digital Library (SEADL)",
        "base_url": "https://sea.lib.niu.edu/",
        "access_type": "external",
        "region": "美国",
        "languages": "lo,th,km,my,pi",
        "description": "北伊利诺伊大学东南亚数字馆藏，含巴利文佛教手稿",
    },
    {
        "code": "dhammachai-tipitaka",
        "name_zh": "法身寺巴利三藏项目",
        "name_en": "Dhammachai Tipitaka Project",
        "base_url": "https://www.dhammachai.org/",
        "access_type": "external",
        "region": "泰国",
        "languages": "pi,th,en",
        "description": "法身寺主持的罗马字巴利三藏校勘项目",
    },
    {
        "code": "oxford-pali",
        "name_zh": "牛津巴利翻译项目",
        "name_en": "Oxford Centre for Buddhist Studies Pali",
        "base_url": "https://ocbs.org/",
        "access_type": "external",
        "region": "英国",
        "languages": "pi,en",
        "description": "牛津佛学研究中心的巴利文翻译与研究项目",
    },
    # ===== 藏文佛学 =====
    {
        "code": "tibetan-buddhist-encyclopedia",
        "name_zh": "藏传佛教百科全书",
        "name_en": "Tibetan Buddhist Encyclopedia",
        "base_url": "https://tibetanbuddhistencyclopedia.com/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,en",
        "description": "全面的藏传佛教在线百科全书",
    },
    {
        "code": "monlam-ai",
        "name_zh": "门兰 AI 藏语平台",
        "name_en": "Monlam AI",
        "base_url": "https://monlam.ai/",
        "access_type": "external",
        "region": "印度",
        "languages": "bo,en",
        "description": "基于 AI 的藏语辞典、翻译与 OCR 工具",
    },
    {
        "code": "openpecha",
        "name_zh": "OpenPecha 开放藏文",
        "name_en": "OpenPecha",
        "base_url": "https://openpecha.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo",
        "description": "开放协作藏文文本数字化平台，机器可读格式",
    },
    {
        "code": "rywiki",
        "name_zh": "让炯耶谢维基",
        "name_en": "Rangjung Yeshe Wiki",
        "base_url": "https://rywiki.tsadra.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,en,sa",
        "description": "藏英佛学辞典 wiki，含大量术语、人名、地名条目",
    },
    {
        "code": "dps-tibetan",
        "name_zh": "数字梵文藏文对照",
        "name_en": "Digital Sanskrit Buddhist Canon - Tibetan",
        "base_url": "https://www.dsbcproject.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,sa",
        "description": "DSBC 项目的藏文佛经对照部分",
    },
    {
        "code": "dharma-dictionary",
        "name_zh": "法语辞典 (Dharma Dictionary)",
        "name_en": "Dharma Dictionary",
        "base_url": "https://rywiki.tsadra.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,en",
        "description": "Erik Pema Kunsang 藏英佛学术语辞典",
    },
    {
        "code": "adarsha-pechamaker",
        "name_zh": "Adarsha 藏文校勘平台",
        "name_en": "Adarsha / PechaMaker",
        "base_url": "https://adarsha.dharma-treasure.org/",
        "access_type": "external",
        "region": "中国",
        "languages": "bo",
        "description": "藏文佛典数字校勘与编辑平台",
    },
    # ===== 梵文/犍陀罗/写本 =====
    {
        "code": "dcs-sanskrit",
        "name_zh": "数字梵文语料库",
        "name_en": "Digital Corpus of Sanskrit (DCS)",
        "base_url": "http://www.sanskrit-linguistics.org/dcs/",
        "access_type": "external",
        "region": "德国",
        "languages": "sa",
        "description": "海德堡大学梵文数字语料库，含词法标注与语法分析",
    },
    {
        "code": "read-workbench",
        "name_zh": "READ 写本研究平台",
        "name_en": "Research Environment for Ancient Documents (READ)",
        "base_url": "https://read.gardens.express/",
        "access_type": "external",
        "region": "澳大利亚",
        "languages": "sa,pgd",
        "description": "悉尼大学古代文献研究数字环境，含犍陀罗语/梵语写本",
    },
    {
        "code": "gandhari-texts-sydney",
        "name_zh": "悉尼犍陀罗语文本",
        "name_en": "Gandhari.org Texts (Sydney)",
        "base_url": "https://gandhari.org/texts",
        "access_type": "external",
        "region": "澳大利亚",
        "languages": "pgd",
        "description": "悉尼犍陀罗语佛教文本数据库与词典",
    },
    {
        "code": "gandhari-lmu",
        "name_zh": "慕尼黑犍陀罗语项目",
        "name_en": "Buddhist Manuscripts from Gandhāra (LMU)",
        "base_url": "https://www.gandhara.indologie.uni-muenchen.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "pgd,sa",
        "description": "慕尼黑大学犍陀罗佛教写本研究项目",
    },
    {
        "code": "diga-bochum",
        "name_zh": "波鸿犍陀罗语数据库",
        "name_en": "DiGA - Digitales Gandhāra (Bochum)",
        "base_url": "https://www.geschkult.fu-berlin.de/en/e/diga/",
        "access_type": "external",
        "region": "德国",
        "languages": "pgd",
        "description": "柏林自由大学犍陀罗数字化档案与数据库",
    },
    {
        "code": "histochtext",
        "name_zh": "历史吐火罗文本库",
        "name_en": "A Historical and Comparative Dictionary of Tocharian",
        "base_url": "https://www.orioles.uni-mainz.de/tocharian/",
        "access_type": "external",
        "region": "德国",
        "languages": "xto,txb",
        "description": "吐火罗语文本与历史比较辞典（含佛教经典吐火罗语译本）",
    },
    {
        "code": "cdsl-cologne",
        "name_zh": "科隆数字梵文辞典",
        "name_en": "Cologne Digital Sanskrit Dictionaries (CDSL)",
        "base_url": "https://www.sanskrit-lexicon.uni-koeln.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "sa,pi,en,de",
        "description": "科隆大学数字梵文辞典集（含摩尼埃-威廉姆斯、阿普特等多部辞典）",
    },
    {
        "code": "sketchengine-sanskrit",
        "name_zh": "SketchEngine 梵文语料",
        "name_en": "SketchEngine Sanskrit Corpus",
        "base_url": "https://www.sketchengine.eu/",
        "access_type": "external",
        "region": "国际",
        "languages": "sa",
        "description": "SketchEngine 平台上的梵文语料库，含佛教文本",
    },
    {
        "code": "titus-thesaurus",
        "name_zh": "TITUS 印欧语文本库",
        "name_en": "TITUS Thesaurus Indogermanischer Text",
        "base_url": "https://titus.uni-frankfurt.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "sa,pi,pgd,xto,txb",
        "description": "法兰克福大学印欧语系文本数据库（含梵/巴/犍陀罗/吐火罗佛教经典）",
    },
    # ===== 汉/日/韩 =====
    {
        "code": "stonesutras",
        "name_zh": "佛教石经项目",
        "name_en": "Buddhist Stone Sutras in China",
        "base_url": "https://www.stonesutras.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,en,de",
        "description": "海德堡学院中国佛教石经数据库（含房山石经、泰山经石峪等）",
    },
    {
        "code": "foguang-dict",
        "name_zh": "佛光大辞典在线",
        "name_en": "Fo Guang Buddhist Dictionary Online",
        "base_url": "https://www.fgs.org.tw/fgs_book/fgs_drser.aspx",
        "access_type": "external",
        "region": "台湾",
        "languages": "zh,en",
        "description": "星云大师主编《佛光大辞典》电子版",
    },
    {
        "code": "nti-reader",
        "name_zh": "NTI Reader 佛学辞典",
        "name_en": "NTI Buddhist Text Reader",
        "base_url": "https://ntireader.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,zh,en",
        "description": "南天佛学翻译学院中英佛学辞典与古文阅读辅助工具",
    },
    {
        "code": "frogbear",
        "name_zh": "FROGBEAR 东亚佛教项目",
        "name_en": "FROGBEAR (UBC)",
        "base_url": "https://frogbear.org/",
        "access_type": "external",
        "region": "加拿大",
        "languages": "lzh,zh,ja,ko,en",
        "description": "UBC 东亚宗教交流数字人文项目 (From the Ground Up)",
    },
    {
        "code": "fosizhi-dila",
        "name_zh": "佛寺志数字典藏",
        "name_en": "Buddhist Temple Gazetteers (DILA)",
        "base_url": "http://buddhistinformatics.dila.edu.tw/fosizhi/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,zh",
        "description": "DILA 佛寺志全文数据库，含中国历代佛教寺院方志",
    },
    {
        "code": "bza-dila",
        "name_zh": "别译杂阿含经数位版",
        "name_en": "BZA Digital (DILA)",
        "base_url": "http://buddhistinformatics.dila.edu.tw/BZA/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,pi",
        "description": "DILA 别译杂阿含经比较研究数位资料库",
    },
    {
        "code": "himalayan-art",
        "name_zh": "喜马拉雅艺术资源",
        "name_en": "Himalayan Art Resources",
        "base_url": "https://www.himalayanart.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "en,bo",
        "description": "全球最大喜马拉雅佛教与印度教艺术图像数据库",
    },
    {
        "code": "jinglu-cbeta",
        "name_zh": "CBETA 经录项目",
        "name_en": "CBETA Jinglu Catalog",
        "base_url": "https://jinglu.cbeta.org/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,zh",
        "description": "CBETA 历代经录资料库（含出三藏记集、开元释教录等）",
    },
    {
        "code": "lapis-lazuli",
        "name_zh": "青金石文本",
        "name_en": "Lapis Lazuli Texts",
        "base_url": "https://www.interlitq.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,sa,pi,bo,en",
        "description": "多语种佛教文本对照阅读平台",
    },
    {
        "code": "lancaster-catalog",
        "name_zh": "Lancaster 韩国佛教典籍目录",
        "name_en": "Lancaster Korean Buddhist Canon Catalog",
        "base_url": "https://www.acmuller.net/descriptive_catalogue/",
        "access_type": "external",
        "region": "美国",
        "languages": "lzh,ko,en",
        "description": "Lewis Lancaster 韩国佛教典籍描述目录",
    },
    {
        "code": "soothill-hodous",
        "name_zh": "Soothill 佛学英汉辞典",
        "name_en": "Soothill-Hodous Dictionary of Chinese Buddhism",
        "base_url": "https://mahajana.net/en/library",
        "access_type": "external",
        "region": "国际",
        "languages": "lzh,en",
        "description": "苏慧廉/何乐益《中国佛学辞典》数字版",
    },
    {
        "code": "acmuller-dict",
        "name_zh": "Muller CJK-English 佛学辞典",
        "name_en": "A. Charles Muller CJK-English Dictionary",
        "base_url": "https://www.acmuller.net/",
        "access_type": "external",
        "region": "日本",
        "languages": "lzh,ja,ko,en",
        "description": "Charles Muller 的 CJK 统合环境辞典（含佛学术语）",
    },
    # ===== 现代翻译/教育/AI =====
    {
        "code": "dharmamitra",
        "name_zh": "法友翻译集",
        "name_en": "Dharmamitra Translations",
        "base_url": "https://www.ثيravada.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "lzh,en",
        "description": "Bhikshu Dharmamitra 汉传佛教经典英译（含六度集经、菩萨地持经等）",
    },
    {
        "code": "dharma-torch",
        "name_zh": "法炬翻译项目",
        "name_en": "Dharma Torch Translation Project",
        "base_url": "https://www.ثيravada.org/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,en",
        "description": "台湾法炬翻译团队的汉传佛教经典英译项目",
    },
    {
        "code": "btts",
        "name_zh": "佛经翻译委员会",
        "name_en": "Buddhist Text Translation Society (BTTS)",
        "base_url": "https://www.buddhisttexts.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "lzh,en",
        "description": "宣化上人创立的佛经翻译委员会翻译著作数字版",
    },
    {
        "code": "encyclopedia-of-buddhism",
        "name_zh": "佛教百科全书",
        "name_en": "Encyclopedia of Buddhism (Macmillan)",
        "base_url": "https://www.encyclopedia.com/religion/encyclopedias-almanacs-transcripts-and-maps/buddhism",
        "access_type": "external",
        "region": "美国",
        "languages": "en",
        "description": "Macmillan 佛教百科全书参考资源",
    },
    {
        "code": "dila-glossaries",
        "name_zh": "DILA 佛学规范术语",
        "name_en": "DILA Buddhist Authority Databases",
        "base_url": "https://authority.dila.edu.tw/",
        "access_type": "api",
        "region": "台湾",
        "languages": "lzh,zh,sa,pi,en",
        "description": "DILA 佛学规范资料库（人名、地名、时间、术语权威数据）",
    },
    {
        "code": "open-buddhist-univ",
        "name_zh": "开放佛学大学",
        "name_en": "Open Buddhist University",
        "base_url": "https://buddhistuniversity.net/",
        "access_type": "external",
        "region": "国际",
        "languages": "en,pi",
        "description": "免费的开放佛学课程与文本库",
    },
    {
        "code": "buddhist-elibrary",
        "name_zh": "佛教电子图书馆",
        "name_en": "BuddhisteLibrary",
        "base_url": "https://www.buddhistelibrary.org/",
        "access_type": "external",
        "region": "澳大利亚",
        "languages": "en",
        "description": "澳大利亚佛教电子图书馆，含多传承文献",
    },
    {
        "code": "h-buddhism-zotero",
        "name_zh": "H-Buddhism 学术文献",
        "name_en": "H-Buddhism Bibliography (H-Net)",
        "base_url": "https://networks.h-net.org/h-buddhism",
        "access_type": "external",
        "region": "美国",
        "languages": "en",
        "description": "H-Net 佛教学术网络的书评、讨论与文献数据库",
    },
    # ===== 学术期刊 =====
    {
        "code": "jbe-ethics",
        "name_zh": "佛教伦理学刊",
        "name_en": "Journal of Buddhist Ethics (JBE)",
        "base_url": "https://blogs.dickinson.edu/buddhistethics/",
        "access_type": "external",
        "region": "美国",
        "languages": "en",
        "description": "全球首个佛学学术电子期刊，开放获取",
    },
    {
        "code": "jgb-global",
        "name_zh": "全球佛教学刊",
        "name_en": "Journal of Global Buddhism",
        "base_url": "https://www.globalbuddhism.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "en",
        "description": "开放获取的全球佛教学术期刊",
    },
    {
        "code": "jiabs",
        "name_zh": "国际佛教学会期刊",
        "name_en": "Journal of the International Association of Buddhist Studies",
        "base_url": "https://journals.ub.uni-heidelberg.de/index.php/jiabs",
        "access_type": "external",
        "region": "德国",
        "languages": "en",
        "description": "国际佛教学会旗舰刊物 (JIABS)，海德堡大学开放获取",
    },
    {
        "code": "jiats",
        "name_zh": "国际藏学会期刊",
        "name_en": "Journal of the International Association for Tibetan Studies",
        "base_url": "https://www.jiats.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "en,bo",
        "description": "国际藏学会学术期刊 (JIATS)，开放获取",
    },
    # ===== 音频/多媒体 =====
    {
        "code": "audiodharma",
        "name_zh": "AudioDharma 法音",
        "name_en": "AudioDharma",
        "base_url": "https://www.audiodharma.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "en",
        "description": "Insight Meditation Center 佛法开示音频档案库",
    },
    {
        "code": "dharmaseed",
        "name_zh": "DharmaSeed 法种",
        "name_en": "Dharma Seed",
        "base_url": "https://dharmaseed.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "en",
        "description": "上座部佛教法话录音数据库，含数万小时音频",
    },
    {
        "code": "free-buddhist-audio",
        "name_zh": "免费佛教音频",
        "name_en": "Free Buddhist Audio",
        "base_url": "https://www.freebuddhistaudio.com/",
        "access_type": "external",
        "region": "英国",
        "languages": "en",
        "description": "Triratna 佛教社区免费佛法音频/视频档案库",
    },
    {
        "code": "tnh-audio",
        "name_zh": "一行禅师法语",
        "name_en": "Thich Nhat Hanh Dharma Talks",
        "base_url": "https://plumvillage.org/library",
        "access_type": "external",
        "region": "法国",
        "languages": "en,vi,fr",
        "description": "梅村道场一行禅师法语开示档案库",
    },
    # ===== 其他地区/特殊资源 =====
    {
        "code": "mitra-ai",
        "name_zh": "MITRA AI 佛教翻译",
        "name_en": "MITRA - Machine Intelligence Translation",
        "base_url": "https://mitra-t.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,sa,lzh,en",
        "description": "AI 辅助的佛经多语翻译平台",
    },
    {
        "code": "mangalam-research",
        "name_zh": "Mangalam 研究中心",
        "name_en": "Mangalam Research Center",
        "base_url": "https://mangalamresearch.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "sa,bo,en",
        "description": "佛教语文学与数字人文研究中心",
    },
    {
        "code": "sakya-research",
        "name_zh": "萨迦研究中心",
        "name_en": "Sakya Research Centre",
        "base_url": "https://sakyaresearch.org/",
        "access_type": "external",
        "region": "印度",
        "languages": "bo,en",
        "description": "萨迦派佛学文献数字化研究项目",
    },
    {
        "code": "kumarajiva-project",
        "name_zh": "鸠摩罗什翻译项目",
        "name_en": "Kumarajiva Project",
        "base_url": "https://kumarajiva.org/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,en",
        "description": "福智团体鸠摩罗什翻译计划（汉传经典英译）",
    },
    {
        "code": "baus-lotus",
        "name_zh": "美国佛教会经典库",
        "name_en": "Buddhist Association of the United States",
        "base_url": "https://www.baus.org/",
        "access_type": "external",
        "region": "美国",
        "languages": "lzh,en",
        "description": "美国佛教会经典翻译与数字化资源",
    },
    {
        "code": "nitartha-dict",
        "name_zh": "Nitartha 藏文辞典",
        "name_en": "Nitartha International Dictionary",
        "base_url": "https://nitartha.net/",
        "access_type": "external",
        "region": "美国",
        "languages": "bo,en",
        "description": "Nitartha International 藏英佛学辞典与教育资源",
    },
    {
        "code": "hamburg-khmer",
        "name_zh": "汉堡柬埔寨写本项目",
        "name_en": "Hamburg Khmer Manuscript Project",
        "base_url": "https://www.manuscript-cultures.uni-hamburg.de/",
        "access_type": "external",
        "region": "德国",
        "languages": "km,pi",
        "description": "汉堡大学柬埔寨巴利文贝叶经写本研究项目",
    },
    {
        "code": "fragile-palm-leaves",
        "name_zh": "脆弱的棕榈叶基金会",
        "name_en": "Fragile Palm Leaves Foundation",
        "base_url": "https://www.fragilepalm.org/",
        "access_type": "external",
        "region": "泰国",
        "languages": "pi,my,th",
        "description": "东南亚巴利文贝叶经保存与数字化基金会",
    },
    {
        "code": "soas-shan",
        "name_zh": "SOAS 掸族写本",
        "name_en": "SOAS Shan Manuscript Collection",
        "base_url": "https://digital.soas.ac.uk/",
        "access_type": "external",
        "region": "英国",
        "languages": "pi,my",
        "description": "伦敦大学亚非学院掸族佛教写本数字化馆藏",
    },
    {
        "code": "chung-tai",
        "name_zh": "中台世界",
        "name_en": "Chung Tai Chan Monastery",
        "base_url": "https://www.ctworld.org.tw/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,zh,en",
        "description": "中台禅寺佛学资源与数字经典",
    },
    {
        "code": "ddm-library",
        "name_zh": "法鼓山数字典藏",
        "name_en": "Dharma Drum Mountain Digital Library",
        "base_url": "https://ddc.shengyen.org/",
        "access_type": "external",
        "region": "台湾",
        "languages": "lzh,zh,en",
        "description": "法鼓山圣严法师著作与佛学典藏数字化",
    },
    {
        "code": "tzu-chi-library",
        "name_zh": "慈济数字典藏",
        "name_en": "Tzu Chi Digital Library",
        "base_url": "https://www.tzuchi.org.tw/",
        "access_type": "external",
        "region": "台湾",
        "languages": "zh,en",
        "description": "慈济基金会证严法师著作与佛学资源数字化",
    },
    {
        "code": "koreanbuddhism",
        "name_zh": "韩国佛教资源门户",
        "name_en": "Korean Buddhism Portal",
        "base_url": "https://www.koreanbuddhism.net/",
        "access_type": "external",
        "region": "韩国",
        "languages": "ko,en",
        "description": "韩国佛教信息门户，含曹溪宗数字典藏",
    },
    {
        "code": "colombo-tripitaka",
        "name_zh": "科伦坡巴利三藏",
        "name_en": "Colombo Tripitaka (Buddha Jayanti)",
        "base_url": "https://www.tripitaka.lk/",
        "access_type": "external",
        "region": "斯里兰卡",
        "languages": "pi,si",
        "description": "斯里兰卡 Buddha Jayanti 巴利三藏完整版",
    },
    {
        "code": "pali-canon-online",
        "name_zh": "巴利佳能在线",
        "name_en": "Pali Canon Online",
        "base_url": "https://www.palicanon.org/",
        "access_type": "external",
        "region": "国际",
        "languages": "pi,en",
        "description": "巴利三藏英译全文在线阅读",
    },
]


def upgrade() -> None:
    conn = op.get_bind()
    inserted = 0
    updated = 0
    for src in SOURCES:
        row = conn.execute(
            __import__("sqlalchemy").text("SELECT id FROM data_sources WHERE code = :code"),
            {"code": src["code"]},
        ).fetchone()
        if row is None:
            conn.execute(
                __import__("sqlalchemy").text(
                    """INSERT INTO data_sources
                       (code, name_zh, name_en, base_url, access_type, region, languages, description, is_active)
                       VALUES (:code, :name_zh, :name_en, :base_url, :access_type, :region, :languages, :description, true)"""
                ),
                src,
            )
            inserted += 1
        else:
            conn.execute(
                __import__("sqlalchemy").text(
                    """UPDATE data_sources
                       SET name_zh = :name_zh, name_en = :name_en, base_url = :base_url,
                           access_type = :access_type, region = :region, languages = :languages,
                           description = :description
                       WHERE code = :code"""
                ),
                src,
            )
            updated += 1
    print(f"✅ Inserted {inserted} new sources, updated {updated} existing")


def downgrade() -> None:
    conn = op.get_bind()
    codes = [s["code"] for s in SOURCES]
    for code in codes:
        conn.execute(
            __import__("sqlalchemy").text("DELETE FROM data_sources WHERE code = :code"),
            {"code": code},
        )
    print(f"🗑️ Removed {len(codes)} sources")
