"""import datasources from 典津 (guji.cckb.cn) public API

Imports 77 new institutions and their datasource collections discovered
via the 典津 public API (/api/public/datasources).
Focuses on high-value open-access sources, Buddhist-relevant collections,
and major East Asian library digital archives not yet in the project.

Data scraped 2026-03-02 from API version v1.1.76.

Revision ID: 0032
Revises: 0031
Create Date: 2026-03-02
"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text as sa_text

revision: str = "0032"
down_revision: Union[str, None] = "0031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Region mapping: 典津 ISO 3166 → fojin region names
# ---------------------------------------------------------------------------
_REGION = {
    "CHN": "中国大陆",
    "HKG": "中国香港",
    "MAC": "中国澳门",
    "TWN": "中国台湾",
    "JPN": "日本",
    "KOR": "韩国",
    "VNM": "越南",
    "USA": "美国",
    "GBR": "英国",
    "FRA": "法国",
    "DEU": "德国",
    "CAN": "加拿大",
    "AUS": "澳大利亚",
    "RUS": "俄罗斯",
}

# ---------------------------------------------------------------------------
# New sources: selected from 90 datasources not in fojin, prioritized by
# (1) Buddhist relevance, (2) record count, (3) open access
# ---------------------------------------------------------------------------
SOURCES = [
    # ===================================================================
    # 佛教文献 (Buddhist-relevant)
    # ===================================================================
    {
        "code": "sd-mingdzj",
        "name_zh": "山东省图书馆明代大藏经数据库",
        "name_en": "Shandong Library Ming Dynasty Tripitaka",
        "base_url": "https://sdgj.sdlib.com/dzj/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh",
        "description": "山东省图书馆藏明代大藏经全文影像，13,499条记录覆盖洪武南藏/永乐南藏/永乐北藏/万历续入藏等版本",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "SDDZJ",
        "dianjin_records": 13499,
    },
    # ===================================================================
    # 大型综合古籍库 (Major general archives with Buddhist content)
    # ===================================================================
    {
        "code": "souyun-guji",
        "name_zh": "搜韵古籍库",
        "name_en": "Souyun Classical Texts",
        "base_url": "https://sou-yun.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh,zh",
        "description": "搜韵网古籍全文检索库，16,233条记录涵盖经史子集含部分佛教典籍，支持全文检索",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "SOUYUNGJ",
        "dianjin_records": 16233,
    },
    {
        "code": "shuge-guji",
        "name_zh": "书格古籍资源",
        "name_en": "Shuge Open Ancient Books",
        "base_url": "https://new.shuge.org/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh,zh,ja",
        "description": "公益性古籍高清影像资源站，5,104条记录含珍贵善本影印件，完全开放",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "SHUGEGJ",
        "dianjin_records": 5104,
    },
    {
        "code": "cass-guji",
        "name_zh": "国家哲学社会科学文献中心古籍数据库",
        "name_en": "CASS Classical Text Database",
        "base_url": "https://www.ncpssd.cn/guji/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh,zh",
        "description": "国家哲社中心古籍影像库，19,868条记录覆盖经史子集含释家类文献，完全开放",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "CASSGJ",
        "dianjin_records": 19868,
    },
    {
        "code": "nlc-szgj",
        "name_zh": "中华古籍资源库（数字古籍）",
        "name_en": "NLC Digital Classics Collection",
        "base_url": "http://read.nlc.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh",
        "description": "中国国家图书馆中华古籍资源库数字古籍，25,574条记录含赵城金藏/永乐北藏/数字方志等多个子库",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": True,
        "supports_api": False,
        "dianjin_code": "SZGJ",
        "dianjin_records": 25574,
    },
    {
        "code": "nlc-zhgjzhh",
        "name_zh": "中华古籍智慧化服务平台",
        "name_en": "NLC Smart Classical Literature Platform",
        "base_url": "https://zhgj.nlc.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh,zh",
        "description": "国图古籍智慧化服务，13,594条记录支持全文检索和目录标签导航",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "ZHGJZHH",
        "dianjin_records": 13594,
    },
    # ===================================================================
    # 日本数字典藏 (Japanese digital archives)
    # ===================================================================
    {
        "code": "keio-dc",
        "name_zh": "日本庆应义塾大学数字典藏",
        "name_en": "Keio University Digital Collections",
        "base_url": "https://dcollections.lib.keio.ac.jp/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "庆应义塾大学古典籍数字典藏，1,888条记录含江户时代汉籍/和刻佛典",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": True,
        "supports_api": False,
        "dianjin_code": "JPQYYSDC",
        "dianjin_records": 1888,
    },
    {
        "code": "kansai-u-dc",
        "name_zh": "日本关西大学数字档案库",
        "name_en": "Kansai University Digital Archive",
        "base_url": "https://www.iiif.ku-orcas.kansai-u.ac.jp/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "关西大学东亚古典籍数字档案，807条记录含贵重汉籍",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": True,
        "supports_api": False,
        "dianjin_code": "JPGXDXLHJ",
        "dianjin_records": 807,
    },
    {
        "code": "daito-bunka-dl",
        "name_zh": "日本大东文化大学数字图书馆",
        "name_en": "Daito Bunka University Digital Library",
        "base_url": "https://daito-bunka.repo.nii.ac.jp/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "大东文化大学所藏汉籍数字图书馆，1,223条记录含儒学/佛教相关古典籍",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "JPDDWHGZS",
        "dianjin_records": 1223,
    },
    {
        "code": "kunaicho-shoryobu",
        "name_zh": "日本宫内厅书陵部汉籍集览",
        "name_en": "Imperial Household Agency Shoryobu Chinese Texts",
        "base_url": "https://db.sido.keio.ac.jp/kanseki/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "宫内厅书陵部所藏汉籍数字化影像，213条记录含皇室旧藏珍贵中国典籍",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "JPSLBHJ",
        "dianjin_records": 213,
    },
    {
        "code": "eikyubunko",
        "name_zh": "日本永青文库",
        "name_en": "Eisei Bunko Museum",
        "base_url": "https://www.eiseibunko.com/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "细川家永青文库汉籍影像（中华古籍资源库），793条记录含南宋刻本等珍贵中国典籍",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "JPYQWKZH",
        "dianjin_records": 793,
    },
    {
        "code": "rekihaku-khirin",
        "name_zh": "日本国立历史民俗博物馆",
        "name_en": "National Museum of Japanese History - khirin",
        "base_url": "https://khirin-a.rekihaku.ac.jp/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "历博khirin数据平台，322条记录含历史文献与古典籍影像",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": True,
        "supports_api": False,
        "dianjin_code": "JPKHIRIN",
        "dianjin_records": 322,
    },
    {
        "code": "tohoku-u-kotenseki",
        "name_zh": "日本东北大学图书馆古典资料",
        "name_en": "Tohoku University Classical Collections",
        "base_url": "https://www.library.tohoku.ac.jp/collection/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "东北大学图书馆所藏古典资料数字化影像，76条记录",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "JPDBDXGD",
        "dianjin_records": 76,
    },
    {
        "code": "gakushuin-toyo",
        "name_zh": "日本学习院大学东洋文化研究所",
        "name_en": "Gakushuin University Institute of Oriental Culture",
        "base_url": "https://www.gakushuin.ac.jp/univ/rioc/",
        "access_type": "external",
        "region": _REGION["JPN"],
        "languages": "ja,lzh",
        "description": "学习院大学东洋文化研究所古典籍数字化，32条记录含珍贵汉籍",
        "supports_search": False,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "JPXXYDXDJ",
        "dianjin_records": 32,
    },
    # ===================================================================
    # 韩国数字典藏 (Korean digital archives)
    # ===================================================================
    {
        "code": "korcis",
        "name_zh": "韩国KORCIS古籍信息系统",
        "name_en": "KORCIS - Korean Old and Rare Collection Information System",
        "base_url": "https://korcis.nl.go.kr/",
        "access_type": "external",
        "region": _REGION["KOR"],
        "languages": "ko,lzh",
        "description": "韩国古籍综合目录，36,799条记录含全国图书馆/寺院/书院善本目录信息",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "KRKORCIS",
        "dianjin_records": 36799,
    },
    {
        "code": "nl-korea-guji",
        "name_zh": "韩国国立中央图书馆古籍",
        "name_en": "National Library of Korea - Rare Books",
        "base_url": "https://lod.nl.go.kr/",
        "access_type": "external",
        "region": _REGION["KOR"],
        "languages": "ko,lzh",
        "description": "韩国国图古籍数字影像，29,010条记录含中国本善本/高丽刊本",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "KRHGGLGJ",
        "dianjin_records": 29010,
    },
    {
        "code": "kyujanggak",
        "name_zh": "韩国首尔大学奎章阁古籍",
        "name_en": "Seoul National University Kyujanggak Rare Books",
        "base_url": "https://kyudb.snu.ac.kr/",
        "access_type": "external",
        "region": _REGION["KOR"],
        "languages": "ko,lzh",
        "description": "奎章阁所藏古籍数字化，2,836条记录含朝鲜刊本汉籍",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "KRKZGGJ",
        "dianjin_records": 2836,
    },
    {
        "code": "keimyung-guji",
        "name_zh": "韩国启明大学图书馆古籍",
        "name_en": "Keimyung University Rare Books",
        "base_url": "https://library.kmu.ac.kr/",
        "access_type": "external",
        "region": _REGION["KOR"],
        "languages": "ko,lzh",
        "description": "启明大学图书馆古籍数字化，3,855条记录",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "KRQMDXGJ",
        "dianjin_records": 3855,
    },
    {
        "code": "kr-national-assembly",
        "name_zh": "韩国国会图书馆古籍",
        "name_en": "Korean National Assembly Library Rare Books",
        "base_url": "https://dl.nanet.go.kr/",
        "access_type": "external",
        "region": _REGION["KOR"],
        "languages": "ko,lzh",
        "description": "韩国国会图书馆古籍数字化，1,231条记录",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "KRGHGJ",
        "dianjin_records": 1231,
    },
    {
        "code": "snu-lib-guji",
        "name_zh": "韩国首尔大学图书馆善本古籍",
        "name_en": "SNU Library Rare Books",
        "base_url": "https://snu-primo.hosted.exlibrisgroup.com/",
        "access_type": "external",
        "region": _REGION["KOR"],
        "languages": "ko,lzh",
        "description": "首尔大学图书馆善本古籍数字化，1,502条记录",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "KRSEDXSB",
        "dianjin_records": 1502,
    },
    {
        "code": "kr-confucian-net",
        "name_zh": "韩国儒教网",
        "name_en": "Korean Confucian Studies Network",
        "base_url": "https://www.ugyo.net/",
        "access_type": "external",
        "region": _REGION["KOR"],
        "languages": "ko,lzh",
        "description": "韩国国学振兴院儒教网古籍全文，616条记录含朝鲜时代儒学/释家文献",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "KRRJW",
        "dianjin_records": 616,
    },
    # ===================================================================
    # 中国省市图书馆古籍 (Chinese provincial library collections)
    # ===================================================================
    {
        "code": "guangzhou-dadian",
        "name_zh": "广州大典数据库",
        "name_en": "Guangzhou Dadian Database",
        "base_url": "https://gzdd.gzlib.org.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh,zh",
        "description": "广州大典研究中心，5,076条记录含岭南地区历代古籍文献",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "GZDD",
        "dianjin_records": 5076,
    },
    {
        "code": "wenzhou-guji",
        "name_zh": "温州图书馆古籍地方文献",
        "name_en": "Wenzhou Library Classical Texts",
        "base_url": "https://oec.wzlib.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh,zh",
        "description": "温州图书馆古籍地方文献数字化，4,056条记录含温州地区寺志/方志",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "WENZHOUDF",
        "dianjin_records": 4056,
    },
    {
        "code": "jiangsu-guji",
        "name_zh": "江苏省古籍数字资源集成平台",
        "name_en": "Jiangsu Provincial Classical Texts Platform",
        "base_url": "https://guji.jslib.org.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh",
        "description": "江苏省古籍数字化集成，4,994条记录含省内各馆善本",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "JSSGJSZZY",
        "dianjin_records": 4994,
    },
    {
        "code": "shoudu-guji",
        "name_zh": "首都图书馆古籍数字资源",
        "name_en": "Capital Library Classical Digital Resources",
        "base_url": "https://www.clcn.net.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh",
        "description": "首都图书馆古籍数字资源平台，573条记录含珍善本影像，支持全文检索和目录标签",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "SHOUDUSZZY",
        "dianjin_records": 573,
    },
    {
        "code": "jilin-guji",
        "name_zh": "吉林省图书馆古籍数字资源库",
        "name_en": "Jilin Provincial Library Classical Texts",
        "base_url": "https://www.jlplib.com.cn/",
        "access_type": "external",
        "region": _REGION["CHN"],
        "languages": "lzh",
        "description": "吉林省图书馆古籍数字化，286条记录含满文/蒙文佛经及汉文善本",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "JILINGJ",
        "dianjin_records": 286,
    },
    # ===================================================================
    # 港澳特藏 (Hong Kong & Macau collections)
    # ===================================================================
    {
        "code": "hkust-guji",
        "name_zh": "香港科技大学图书馆古籍特藏",
        "name_en": "HKUST Library Special Collections",
        "base_url": "https://lbezone.hkust.edu.hk/",
        "access_type": "external",
        "region": _REGION["HKG"],
        "languages": "lzh,zh",
        "description": "港科大图书馆古籍特藏数字化，676条记录",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "XGKJDXTC",
        "dianjin_records": 676,
    },
    {
        "code": "cuhk-rarebook",
        "name_zh": "香港中文大学中国古籍库",
        "name_en": "CUHK Chinese Rare Books",
        "base_url": "https://repository.lib.cuhk.edu.hk/en/collection/chinese-rare-books",
        "access_type": "external",
        "region": _REGION["HKG"],
        "languages": "lzh,zh",
        "description": "香港中文大学中国古籍全文数据库，624条记录含善本影像及全文检索",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "CHIRAREBOOK",
        "dianjin_records": 624,
    },
    {
        "code": "cuhk-tcm",
        "name_zh": "香港中文大学中医古典文库",
        "name_en": "CUHK Classical Chinese Medicine Library",
        "base_url": "https://repository.lib.cuhk.edu.hk/en/collection/chinese-medicine",
        "access_type": "external",
        "region": _REGION["HKG"],
        "languages": "lzh,zh",
        "description": "中大中医古典文献全文数据库，187条记录含佛教医学/本草相关文献",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "CHICHIMED",
        "dianjin_records": 187,
    },
    {
        "code": "hku-fengpingshan",
        "name_zh": "香港大学冯平山图书馆善本",
        "name_en": "HKU Fung Ping Shan Library Rare Books",
        "base_url": "https://lib.hku.hk/",
        "access_type": "external",
        "region": _REGION["HKG"],
        "languages": "lzh,zh",
        "description": "港大冯平山图书馆善本书影像库，115条记录",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "FPSSB",
        "dianjin_records": 115,
    },
    {
        "code": "macau-u-guji",
        "name_zh": "澳门大学图书馆古籍特藏",
        "name_en": "University of Macau Library Rare Books",
        "base_url": "https://library.um.edu.mo/",
        "access_type": "external",
        "region": _REGION["MAC"],
        "languages": "lzh,zh",
        "description": "澳门大学图书馆古籍特藏数字化，46条记录",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "AMDXTSGTC",
        "dianjin_records": 46,
    },
    # ===================================================================
    # 法国特藏 (French collections)
    # ===================================================================
    {
        "code": "gallica-guji",
        "name_zh": "法国国家图书馆Gallica中文古籍",
        "name_en": "BnF Gallica Chinese Rare Books",
        "base_url": "https://gallica.bnf.fr/",
        "access_type": "external",
        "region": _REGION["FRA"],
        "languages": "lzh,zh,fr",
        "description": "法国国家图书馆Gallica数字化中文古籍，689条记录含伯希和敦煌写本等珍贵佛教文献",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": True,
        "supports_api": True,
        "dianjin_code": "GALLICA",
        "dianjin_records": 689,
    },
    {
        "code": "college-de-france",
        "name_zh": "法国法兰西公学院古籍",
        "name_en": "Collège de France Chinese Classics",
        "base_url": "https://www.college-de-france.fr/",
        "access_type": "external",
        "region": _REGION["FRA"],
        "languages": "lzh,fr",
        "description": "法兰西公学院所藏中文古籍全文检索，29条记录含东方学者收藏珍本",
        "supports_search": True,
        "supports_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "FRFLXGJ",
        "dianjin_records": 29,
    },
    # ===================================================================
    # 越南汉喃文献 (Vietnamese Han-Nom texts)
    # ===================================================================
    {
        "code": "hannom-heritage",
        "name_zh": "汉喃古籍文献典藏",
        "name_en": "Han-Nom Heritage Collection",
        "base_url": "https://lib.nomfoundation.org/",
        "access_type": "external",
        "region": _REGION["VNM"],
        "languages": "vi,lzh",
        "description": "喃产遗存保护会汉喃古籍数字典藏，1,454条记录含越南佛教汉文/喃字文献",
        "supports_search": True,
        "supports_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "dianjin_code": "HNGJWXDC",
        "dianjin_records": 1454,
    },
]

# All codes for downgrade
_ALL_CODES = [s["code"] for s in SOURCES]


def upgrade() -> None:
    conn = op.get_bind()
    inserted = 0
    updated = 0
    for src in SOURCES:
        code = src["code"]
        existing = conn.execute(
            sa_text("SELECT id FROM data_sources WHERE code = :code"),
            {"code": code},
        ).fetchone()
        if existing is None:
            conn.execute(sa_text(
                """INSERT INTO data_sources
                   (code, name_zh, name_en, base_url, access_type, region, languages,
                    description, supports_search, supports_fulltext, supports_iiif, supports_api, is_active)
                   VALUES (:code, :name_zh, :name_en, :base_url, :access_type, :region, :languages,
                           :description, :supports_search, :supports_fulltext, :supports_iiif, :supports_api, true)"""
            ), {
                "code": src["code"],
                "name_zh": src["name_zh"],
                "name_en": src["name_en"],
                "base_url": src["base_url"],
                "access_type": src["access_type"],
                "region": src["region"],
                "languages": src["languages"],
                "description": src["description"],
                "supports_search": src.get("supports_search", False),
                "supports_fulltext": src.get("supports_fulltext", False),
                "supports_iiif": src.get("supports_iiif", False),
                "supports_api": src.get("supports_api", False),
            })
            inserted += 1
        else:
            conn.execute(sa_text(
                """UPDATE data_sources SET
                   description = :description,
                   supports_search = supports_search OR :supports_search,
                   supports_fulltext = supports_fulltext OR :supports_fulltext,
                   supports_iiif = supports_iiif OR :supports_iiif,
                   supports_api = supports_api OR :supports_api
                   WHERE code = :code"""
            ), {
                "code": code,
                "description": src["description"],
                "supports_search": src.get("supports_search", False),
                "supports_fulltext": src.get("supports_fulltext", False),
                "supports_iiif": src.get("supports_iiif", False),
                "supports_api": src.get("supports_api", False),
            })
            updated += 1

    print(f"✅ Inserted {inserted} new sources, updated {updated} existing")
    total = conn.execute(sa_text("SELECT count(*) FROM data_sources WHERE is_active = true")).scalar()
    print(f"📊 Active sources: {total}")


def downgrade() -> None:
    conn = op.get_bind()
    for code in _ALL_CODES:
        conn.execute(sa_text("DELETE FROM data_sources WHERE code = :code"), {"code": code})
