"""Add curated data sources from bookmarks.

Adds ~35 high-value digital Buddhist text resources selected from user bookmarks.

Revision ID: 0081
Revises: 0080
Create Date: 2026-03-06
"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text as sa_text

revision: str = "0081"
down_revision: Union[str, None] = "0080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_SOURCES = [
    # ── 中国大陆 ──
    {
        "code": "gj-cool",
        "name_zh": "古籍酷",
        "name_en": "Ancient Texts Cool",
        "base_url": "https://gj.cool/",
        "description": "古籍全文检索与在线阅读平台，收录大量佛教典籍，支持关键词搜索。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "lib-fo",
        "name_zh": "佛來寶",
        "name_en": "FoLib Buddhist Library",
        "base_url": "https://lib.fo/",
        "description": "佛教经典数字图书馆，提供佛经在线阅读、搜索与文档管理功能。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "fashi-ai",
        "name_zh": "法海搜索",
        "name_en": "FaShi AI Buddhist Search",
        "base_url": "https://fashi.ai/",
        "description": "基于AI语义理解的佛教文献智能搜索引擎，支持佛经与法师开示的语义检索。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_api": True,
    },
    {
        "code": "xianmi-wenku",
        "name_zh": "显密文库",
        "name_en": "Xianmi Buddhist Text Library",
        "base_url": "http://read.goodweb.net.cn/",
        "description": "佛教显密各宗经论文库，提供经论原文、法师著述、修行指导等在线阅读。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "bohanjingzang",
        "name_zh": "般汗经藏（龙藏）",
        "name_en": "Bohan Jingzang (Dragon Tripitaka)",
        "base_url": "https://www.bohanjingzang.com/",
        "description": "清代龙藏数字化全文阅读平台，提供《龙藏》经文在线浏览与检索。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "srjz",
        "name_zh": "深入经藏",
        "name_en": "Deep into Sutras",
        "base_url": "https://www.srjz.top/",
        "description": "佛经在线阅读与全文检索平台，提供分类浏览和关键词搜索。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "sutra-mobi",
        "name_zh": "巴利经藏",
        "name_en": "Pali Nikaya Chinese",
        "base_url": "https://sutra.mobi/",
        "description": "巴利语尼柯耶经典中文翻译在线阅读，覆盖长部、中部、相应部、增支部、小部。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "pi,zh",
        "supports_search": False,
    },
    {
        "code": "fanfoyan-dict",
        "name_zh": "梵佛词典",
        "name_en": "Sanskrit Buddhist Dictionary",
        "base_url": "https://dict.fanfoyan.com/",
        "description": "梵文佛教术语在线词典，提供梵汉对照查询，辅助佛典梵文阅读与研究。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "sa,zh",
        "supports_search": True,
    },
    {
        "code": "fdict-cn",
        "name_zh": "梵佛词典(fdict)",
        "name_en": "FDict Sanskrit Buddhist Dictionary",
        "base_url": "https://fdict.cn/",
        "description": "梵文佛教词汇在线检索系统，支持梵中英多语查询。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "sa,zh,en",
        "supports_search": True,
    },
    {
        "code": "monktalks",
        "name_zh": "僧言僧语佛典阅读",
        "name_en": "MonkTalks Sutra Reading",
        "base_url": "https://www.monktalks.net/",
        "description": "佛教经典在线阅读平台，提供经文原文与白话对照阅读。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": False,
    },
    {
        "code": "crta-info",
        "name_zh": "中国宗教典籍权威 CRTA",
        "name_en": "Chinese Religious Texts Authority",
        "base_url": "https://crta.info/",
        "description": "中国宗教典籍权威目录Wiki，含佛教典籍元数据、版本信息与关联数据。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "zh,en",
        "supports_search": True,
    },
    {
        "code": "kosa-arpcn",
        "name_zh": "俱舍注释对照",
        "name_en": "Abhidharmakosa Commentary Parallel",
        "base_url": "https://arpcn.top/kosa/",
        "description": "《俱舍论》多版本注释对照阅读平台，支持不同注疏并列比较。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": False,
    },
    {
        "code": "sxlib-ztbk",
        "name_zh": "陕西佛教祖庭文化资源宝库",
        "name_en": "Shaanxi Buddhist Ancestral Temple Cultural Resources",
        "base_url": "https://www.sxlib.org.cn/dfzy/sxfjwhzybk/",
        "description": "陕西省图书馆建设的佛教祖庭文化专题数据库，含祖庭文献、碑刻、图像资料。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "zh",
        "supports_search": True,
    },
    {
        "code": "fodocs-list",
        "name_zh": "寂光云流Lib",
        "name_en": "FoDocs Buddhist E-Resource Hub",
        "base_url": "https://list.fodocs.com/",
        "description": "佛教电子文献资源聚合平台，整理和传递各类佛教数字化资源。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "zh",
        "supports_search": False,
    },
    # ── 中国台湾 ──
    {
        "code": "hsing-yun-books",
        "name_zh": "星云大师全集",
        "name_en": "Venerable Hsing Yun Complete Works",
        "base_url": "https://books.masterhsingyun.org/",
        "description": "星云大师全部著作数字化平台，4000余万字著述全文检索，含讲经、论文、开示等。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "zh",
        "supports_search": True,
    },
    {
        "code": "shengyen-archive",
        "name_zh": "圣严法师数位典藏",
        "name_en": "Master Sheng Yen Digital Archive",
        "base_url": "https://www.shengyen.org/",
        "description": "法鼓山圣严法师全部著作与讲经数字典藏平台，含书籍、开示、影音资料。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "zh",
        "supports_search": True,
    },
    {
        "code": "ymfz",
        "name_zh": "圆满法藏",
        "name_en": "Complete Dharma Treasury",
        "base_url": "https://www.ymfz.org/",
        "description": "佛经今译与原典对照阅读平台，提供经文白话翻译与原文并列显示。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "cbeta-concordance",
        "name_zh": "CBETA词汇搜寻与分析",
        "name_en": "CBETA Concordance",
        "base_url": "https://cbetaconcordance.dila.edu.tw/",
        "description": "DILA建设的CBETA佛典词汇索引与频率分析工具，支持词频统计、用例检索、共现分析。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "dedu-dila",
        "name_zh": "大般若经对读 DEDU",
        "name_en": "DEDU Prajnaparamita Parallel Reading",
        "base_url": "https://dedu.dila.edu.tw/",
        "description": "DILA建设的大般若经多语言对读平台，支持梵汉藏多版本逐段对照。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,sa,bo",
        "supports_search": True,
    },
    {
        "code": "lrannotations",
        "name_zh": "广论四家合注浅释",
        "name_en": "Lamrim Annotations",
        "base_url": "https://lrannotations.org/",
        "description": "《菩提道次第广论》四家合注对照阅读平台，支持藏汉原文与注释并列显示。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "bo,zh",
        "supports_search": True,
    },
    {
        "code": "amec-amrtf",
        "name_zh": "大慈恩月光藏",
        "name_en": "AMRTF Moonlight Treasury",
        "base_url": "https://amec.amrtf.org/",
        "description": "大慈恩译经基金会藏汉佛典对照数字平台，提供藏文经典与汉译对照阅读。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "bo,zh",
        "supports_search": True,
    },
    {
        "code": "buddhasaids",
        "name_zh": "佛说·佛书典藏与导读",
        "name_en": "BuddhaSaids Digital Collection",
        "base_url": "https://buddhasaids.com/",
        "description": "佛教经典导读与数字化典藏平台，提供经文介绍、原文阅读与导读解析。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "bfnn-book",
        "name_zh": "般若文海",
        "name_en": "Prajna Sea of Texts",
        "base_url": "https://book.bfnn.org/",
        "description": "报佛恩网电子佛书全文库，大量佛教经论、法师著述繁体全文在线阅读。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": False,
    },
    {
        "code": "suttaworld",
        "name_zh": "佛学世界（网路藏经阁）",
        "name_en": "Sutta World Online Tripitaka",
        "base_url": "http://www.suttaworld.org/",
        "description": "永乐北藏、乾隆大藏经、大正藏、卍续藏等多部大藏经在线阅读平台。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    {
        "code": "youfun-sinica",
        "name_zh": "遊方·历代僧传僧人出行叙述",
        "name_en": "YouFun Monk Travel Narratives DB",
        "base_url": "https://youfun.litphil.sinica.edu.tw/",
        "description": "中研院建设的历代僧传僧人行旅叙述专题数据库，可视化呈现僧侣行迹与历史地理。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
    },
    # ── 中国香港 ──
    {
        "code": "bcbs-eduhk",
        "name_zh": "梵汉对勘双语语料库",
        "name_en": "Buddhist Chinese-Sanskrit Bilingual Corpus",
        "base_url": "https://bcbs.eduhk.hk/",
        "description": "香港教育大学梵汉佛典双语对勘语料库，支持梵文与汉译经文逐句平行对照。",
        "access_type": "external",
        "region": "中国香港",
        "languages": "sa,lzh",
        "supports_search": True,
    },
    {
        "code": "tiantai-lib",
        "name_zh": "天台文库",
        "name_en": "Tiantai Buddhist Library",
        "base_url": "http://ttlib.buddhism.org.hk/",
        "description": "香港天台宗专题佛学文献在线阅读，收录天台宗经论、祖师著述等。",
        "access_type": "external",
        "region": "中国香港",
        "languages": "lzh,zh",
        "supports_search": False,
    },
    # ── 日本 ──
    {
        "code": "komazawa-zenseki",
        "name_zh": "驹泽大学禅籍目录电子版",
        "name_en": "Komazawa University Zen Texts Digital Catalogue",
        "base_url": "https://zenseki.komazawa-u.ac.jp/",
        "description": "驹泽大学禅宗典籍电子目录数据库，收录禅宗文献目录与版本信息。",
        "access_type": "external",
        "region": "日本",
        "languages": "ja,lzh",
        "supports_search": True,
    },
    {
        "code": "hobogirin",
        "name_zh": "法宝义林 Hôbôgirin",
        "name_en": "Hôbôgirin Digital Buddhist Encyclopedia",
        "base_url": "https://tripitaka.l.u-tokyo.ac.jp/hbgrn/",
        "description": "东京大学法宝义林佛教百科数字版，法日双语佛学百科全书。",
        "access_type": "external",
        "region": "日本",
        "languages": "ja,fr",
        "supports_search": True,
    },
    {
        "code": "bauda-ai",
        "name_zh": "Bauda AI 佛教RAG",
        "name_en": "Bauda AI Buddhist RAG",
        "base_url": "https://agni.dhii.jp/bd-rag/",
        "description": "日本数字人文研究所佛教文献AI检索增强系统，基于RAG技术智能检索佛教文献。",
        "access_type": "external",
        "region": "日本",
        "languages": "en,ja",
        "supports_search": True,
        "supports_api": True,
    },
    # ── 美国 ──
    {
        "code": "princeton-yongle",
        "name_zh": "普林斯顿大学永乐北藏数字化",
        "name_en": "Princeton Yongle Northern Canon Digital",
        "base_url": "https://dpul.princeton.edu/eastasian/browse/ming-bei-zang",
        "description": "普林斯顿大学东亚图书馆永乐北藏高清数字化影像，提供全藏逐页浏览。",
        "access_type": "external",
        "region": "美国",
        "languages": "lzh",
        "supports_search": False,
        "supports_iiif": True,
    },
    {
        "code": "princeton-qisha",
        "name_zh": "普林斯顿大学碛砂藏数字化",
        "name_en": "Princeton Qisha Canon Digital",
        "base_url": "https://dpul.princeton.edu/eastasian/browse/qisha-da-zang-jing",
        "description": "普林斯顿大学碛砂大藏经高清数字化影像，宋元刻本珍贵影像全藏浏览。",
        "access_type": "external",
        "region": "美国",
        "languages": "lzh",
        "supports_search": False,
        "supports_iiif": True,
    },
    {
        "code": "sambhota-dict",
        "name_zh": "桑泊词典",
        "name_en": "Sambhota Dictionary Search",
        "base_url": "https://dict.dharma-treasure.org/",
        "description": "藏文佛学术语多语词典搜索平台，支持藏英中多语对照查询。",
        "access_type": "external",
        "region": "美国",
        "languages": "bo,en,zh",
        "supports_search": True,
    },
    # ── 比利时 ──
    {
        "code": "dmct-ghent",
        "name_zh": "中古写本资料库 DMCT",
        "name_en": "Database of Medieval Chinese Texts",
        "base_url": "https://www.database-of-medieval-chinese-texts.be/",
        "description": "根特大学中古中国写本数据库，含大量敦煌佛教写本、禅宗语录等文献的结构化数据。",
        "access_type": "external",
        "region": "比利时",
        "languages": "lzh,en",
        "supports_search": True,
    },
    # ── 德国 ── (buddhanexus already exists in DB, skipped)
    # ── 印度 ──
    {
        "code": "vri-tipitaka",
        "name_zh": "内观研究院巴利三藏 CSCD",
        "name_en": "VRI Chattha Sangayana Tipitaka",
        "base_url": "https://www.vridhamma.org/",
        "description": "内观研究院第六次结集巴利三藏全文数据库(CSCD)，提供巴利原典全文检索。",
        "access_type": "external",
        "region": "印度",
        "languages": "pi",
        "supports_search": True,
    },
    # ── 国际 ──
    {
        "code": "encyclopedia-buddhism",
        "name_zh": "佛教百科全书",
        "name_en": "Encyclopedia of Buddhism",
        "base_url": "https://encyclopediaofbuddhism.org/",
        "description": "开放式佛教百科全书Wiki，涵盖教义、人物、典籍、历史、宗派等条目。",
        "access_type": "external",
        "region": "国际",
        "languages": "en",
        "supports_search": True,
    },
]


def upgrade() -> None:
    conn = op.get_bind()
    for s in NEW_SOURCES:
        params = {
            "code": s["code"],
            "name_zh": s["name_zh"],
            "name_en": s.get("name_en", ""),
            "base_url": s["base_url"],
            "description": s.get("description", ""),
            "access_type": s.get("access_type", "external"),
            "region": s.get("region", ""),
            "languages": s.get("languages", ""),
            "supports_search": s.get("supports_search", False),
            "supports_fulltext": s.get("supports_fulltext", False),
            "has_local_fulltext": s.get("has_local_fulltext", False),
            "has_remote_fulltext": s.get("has_remote_fulltext", False),
            "supports_iiif": s.get("supports_iiif", False),
            "supports_api": s.get("supports_api", False),
            "is_active": s.get("is_active", True),
        }
        conn.execute(
            sa_text("""
                INSERT INTO data_sources (
                    code, name_zh, name_en, base_url, description,
                    access_type, region, languages,
                    supports_search, supports_fulltext,
                    has_local_fulltext, has_remote_fulltext,
                    supports_iiif, supports_api, is_active
                ) VALUES (
                    :code, :name_zh, :name_en, :base_url, :description,
                    :access_type, :region, :languages,
                    :supports_search, :supports_fulltext,
                    :has_local_fulltext, :has_remote_fulltext,
                    :supports_iiif, :supports_api, :is_active
                ) ON CONFLICT (code) DO NOTHING
            """),
            params,
        )


def downgrade() -> None:
    conn = op.get_bind()
    codes = [s["code"] for s in NEW_SOURCES]
    for code in codes:
        conn.execute(
            sa_text("DELETE FROM data_sources WHERE code = :code"),
            {"code": code},
        )
