"""Add curated data sources from bookmarks (batch 2).

Second-pass review: adds ~21 additional high-value Buddhist digital text
resources missed in the first batch (0081).

Revision ID: 0082
Revises: 0081
Create Date: 2026-03-06
"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text as sa_text

revision: str = "0082"
down_revision: Union[str, None] = "0081"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_SOURCES = [
    # ── 综合/国际 ──
    {
        "code": "cter-info",
        "name_zh": "汉文佛教大藏经电子资源",
        "name_en": "Chinese Tripitaka Electronic Resources (CTER)",
        "base_url": "https://cter.info/",
        "description": "汉文佛教大藏经电子资源导航与整合平台，系统性收集和整理各种汉文大藏经数字化资源的元数据与链接，是查找藏经电子化资源的重要入口。",
        "access_type": "external",
        "region": "国际",
        "languages": "zh,en",
        "supports_search": True,
        "supports_fulltext": False,
        "has_local_fulltext": False,
        "has_remote_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "titus-frankfurt",
        "name_zh": "TITUS文本数据库",
        "name_en": "TITUS (Thesaurus Indogermanischer Text- und Sprachmaterialien)",
        "base_url": "http://titus.uni-frankfurt.de/indexe.htm",
        "description": "法兰克福大学印欧语系文本和语言资料汇编，收录大量梵文、巴利文、吐火罗文等佛教相关古典语言文献全文语料。",
        "access_type": "external",
        "region": "德国",
        "languages": "sa,pi,xto,txb,mul",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "itlr-net",
        "name_zh": "印藏词汇资源",
        "name_en": "Indo-Tibetan Lexical Resource (ITLR)",
        "base_url": "https://www.itlr.net/",
        "description": "印度-西藏词汇资源数据库，提供梵藏对照术语查询，涵盖佛教翻译学和术语研究的核心词汇。",
        "access_type": "external",
        "region": "国际",
        "languages": "sa,bo,en",
        "supports_search": True,
        "supports_fulltext": False,
        "has_local_fulltext": False,
        "has_remote_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "bib-buddhiststudies",
        "name_zh": "中国佛教数字目录",
        "name_en": "Digital Catalogue of Chinese Buddhism",
        "base_url": "https://bib.buddhiststudies.net/",
        "description": "中国佛教文献数字目录，提供佛教经录、书目的系统化数字索引，是佛教文献学研究的重要工具。",
        "access_type": "external",
        "region": "国际",
        "languages": "zh,en",
        "supports_search": True,
        "supports_fulltext": False,
        "has_local_fulltext": False,
        "has_remote_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "tibetanclassics",
        "name_zh": "藏文经典翻译研究院",
        "name_en": "Institute of Tibetan Classics",
        "base_url": "https://tibetanclassics.org/",
        "description": "Thupten Jinpa主持的藏文经典研究所，推动Library of Tibetan Classics系列藏文经典英译出版项目。",
        "access_type": "external",
        "region": "加拿大",
        "languages": "bo,en",
        "supports_search": False,
        "supports_fulltext": False,
        "has_local_fulltext": False,
        "has_remote_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "rigzod",
        "name_zh": "Rigzod藏文文献库",
        "name_en": "Rigzod Tibetan Text Repository",
        "base_url": "https://rigzod.net/",
        "description": "藏文佛教文献数字图书馆，提供宁玛派等藏传佛教经典文本的在线阅读和下载。",
        "access_type": "external",
        "region": "国际",
        "languages": "bo",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "pandita-translation",
        "name_zh": "Pandita藏译汉翻译中心",
        "name_en": "Pandita Translation",
        "base_url": "https://www.panditatranslation.org/",
        "description": "专注于藏文佛典汉译的翻译项目，提供藏文经典的中文翻译文本在线阅读。",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,zh",
        "supports_search": False,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "samye-translations",
        "name_zh": "桑耶翻译",
        "name_en": "Samye Translations",
        "base_url": "https://www.samyetranslations.org/",
        "description": "藏传佛教经典翻译项目，提供藏文佛教重要论典的英文翻译在线阅读。",
        "access_type": "external",
        "region": "国际",
        "languages": "bo,en",
        "supports_search": False,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    # ── 越南 ──
    {
        "code": "daitangkinh",
        "name_zh": "灵山法宝大藏经（越文）",
        "name_en": "Linh Son Tripitaka (Vietnamese)",
        "base_url": "https://www.daitangkinh.org/",
        "description": "越南灵山寺主持的越文大藏经数字化项目，是目前最完整的越南语佛教大藏经在线资源。",
        "access_type": "external",
        "region": "越南",
        "languages": "vi,lzh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "siteofenlightenment",
        "name_zh": "启迪之地",
        "name_en": "Site of Enlightenment",
        "base_url": "https://siteofenlightenment.org/",
        "description": "多语种佛教三藏在线阅读平台，提供越文、中文古文、巴利文等多种语言的佛教经典。",
        "access_type": "external",
        "region": "越南",
        "languages": "vi,lzh,pi,mul",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    # ── 中国大陆 ──
    {
        "code": "fodian-net",
        "name_zh": "华夏佛典宝库",
        "name_en": "Fodian.net Buddhist Text Repository",
        "base_url": "http://www.fodian.net/",
        "description": "佛教典籍在线阅读平台，收录大量佛经全文，支持检索与在线阅读。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "fodzj-lianhai",
        "name_zh": "清净莲海大藏经",
        "name_en": "Qingjing Lianhai Tripitaka",
        "base_url": "http://fodzj.jixiangyun.com/",
        "description": "提供大正藏、龙藏、嘉兴藏等多部大藏经的全文在线阅读，是综合性汉文藏经阅读平台。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "fodizi",
        "name_zh": "佛弟子文库",
        "name_en": "Buddhist Disciple Library",
        "base_url": "http://www.fodizi.net/",
        "description": "大型佛教文章与书籍在线阅读平台，收录经典注解、法师开示、佛学入门等各类佛教文献。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "dunhuang-snupg",
        "name_zh": "敦煌文献专题数据库",
        "name_en": "Dunhuang Manuscripts Thematic Database",
        "base_url": "https://dunhuang.snupg.com/",
        "description": "首都师范大学电子文献研究所建设的敦煌文献专题数据库，提供敦煌写本文献（含大量佛教写经）的全文检索与影像浏览。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "dunhuang-hanji",
        "name_zh": "敦煌文献数字图书馆",
        "name_en": "Dunhuang Digital Library of Literature",
        "base_url": "http://dunhuang.hanjilibrary.com/",
        "description": "汉籍图书馆托管的敦煌文献数字图书馆，提供敦煌写卷文献的数字化浏览，包含大量佛教写本。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": False,
        "has_local_fulltext": False,
        "has_remote_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "ahanjing",
        "name_zh": "阿含经在线",
        "name_en": "Agama Sutras Online",
        "base_url": "http://www.ahanjing.com/",
        "description": "阿含经专题在线阅读平台，提供四部阿含经全文及相关研究资料。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    # ── 中国台湾 ──
    {
        "code": "sutra-humanistic",
        "name_zh": "佛梅電子大藏經",
        "name_en": "Humanistic Buddhism E-Tripitaka",
        "base_url": "http://sutra.humanistic-bud.org/",
        "description": "佛梅电子大藏经普及版，提供汉文大藏经数字化全文在线阅读。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "sutrapearls",
        "name_zh": "佛典妙供",
        "name_en": "Sutra Pearls",
        "base_url": "http://www.sutrapearls.org/",
        "description": "佛教典籍分类整理与全文阅读平台，按主题分类提供经律论等佛典在线阅读。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    # ── 日本 ──
    {
        "code": "seiten-icho",
        "name_zh": "圣教电子化研究会",
        "name_en": "Society for Digitalization of Sacred Texts",
        "base_url": "https://seiten.icho.gr.jp/",
        "description": "日本真宗系圣教电子化研究会，致力于净土真宗经典圣教文献的电子化，提供全文在线阅读。",
        "access_type": "external",
        "region": "日本",
        "languages": "ja",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    # ── 美国 ──
    {
        "code": "vajrabodhisea",
        "name_zh": "金刚菩提海",
        "name_en": "Vajra Bodhi Sea",
        "base_url": "https://vajrabodhisea.org/",
        "description": "万佛城《金刚菩提海》杂志数字化，提供历年佛教期刊文章全文在线阅读，涵盖经典翻译、法师开示等。",
        "access_type": "external",
        "region": "美国",
        "languages": "zh,en",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "book853",
        "name_zh": "七叶佛教书舍",
        "name_en": "Seven Leaves Buddhist Bookstore",
        "base_url": "http://www.book853.com/",
        "description": "大型佛教电子书在线阅读与下载平台，收录经典、论著、法师著作等各类佛教书籍。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "zh",
        "supports_search": True,
        "supports_fulltext": True,
        "has_local_fulltext": False,
        "has_remote_fulltext": True,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    # ── 佛教石窟/石刻 ──
    {
        "code": "yungang-digital",
        "name_zh": "云冈石窟数字博物馆",
        "name_en": "Yungang Grottoes Digital Museum",
        "base_url": "https://www.yungang.org/dzb/index.html",
        "description": "世界文化遗产云冈石窟官方数字博物馆，提供石窟造像3D数字化浏览与窟龛信息查询，对佛教艺术研究具有重要价值。",
        "access_type": "external",
        "region": "中国大陆",
        "languages": "zh",
        "supports_search": False,
        "supports_fulltext": False,
        "has_local_fulltext": False,
        "has_remote_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
    {
        "code": "ihp-buddhist-rubbings",
        "name_zh": "佛教石刻造像拓本数据库",
        "name_en": "Buddhist Stone Sculpture Rubbings (IHP, Academia Sinica)",
        "base_url": "https://rub.ihp.sinica.edu.tw/~buddhism/",
        "description": "中研院历史语言研究所建设的佛教石刻造像拓本专题数据库，收录大量佛教碑刻、造像题记拓本影像。",
        "access_type": "external",
        "region": "中国台湾",
        "languages": "lzh,zh",
        "supports_search": True,
        "supports_fulltext": False,
        "has_local_fulltext": False,
        "has_remote_fulltext": False,
        "supports_iiif": False,
        "supports_api": False,
        "sort_order": 0,
        "is_active": True,
    },
]

CODES = [s["code"] for s in NEW_SOURCES]


def upgrade() -> None:
    conn = op.get_bind()
    for s in NEW_SOURCES:
        conn.execute(
            sa_text("""
                INSERT INTO data_sources (
                    code, name_zh, name_en, base_url, description,
                    access_type, region, languages,
                    supports_search, supports_fulltext,
                    has_local_fulltext, has_remote_fulltext,
                    supports_iiif, supports_api, sort_order, is_active
                ) VALUES (
                    :code, :name_zh, :name_en, :base_url, :description,
                    :access_type, :region, :languages,
                    :supports_search, :supports_fulltext,
                    :has_local_fulltext, :has_remote_fulltext,
                    :supports_iiif, :supports_api, :sort_order, :is_active
                )
                ON CONFLICT (code) DO NOTHING
            """),
            s,
        )


def downgrade() -> None:
    conn = op.get_bind()
    for code in CODES:
        conn.execute(
            sa_text("DELETE FROM data_sources WHERE code = :code"),
            {"code": code},
        )
